In [59]:
import numpy as np
from numpy.linalg import svd

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


In [64]:
a = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(f'Матрица А: {a}')

Матрица А: [[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [65]:
u, s, w = svd(a)
d = np.zeros_like(a, dtype=float)
d[np.diag_indices(min(a.shape))] = s
v = w.T
print(f'Матрица U:\n {u}\nМатрица D:\n {d}\nМатрица V:\n {v}')

Матрица U:
 [[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица D:
 [[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица V:
 [[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [63]:
print(f'Проверка:\n {u @ d @ v.T}')

Проверка:
 [[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [68]:
# норма Евклида совпадает с первым диагональным элементом матрицы D
a_norm_e = s[0]
a_norm_e

8.824868854820442

In [77]:
# норма Фробениуса равна корню квадратному из суммы диагональных элементов матрицы D
a_norm_f = np.sqrt(np.sum([el**2 for el in s]))
a_norm_f

11.045361017187261