In [14]:
import numpy as np
from numpy.linalg import eig

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$
    


1. Найдем собственные значения 

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)+2\cdot 6=0,$$

$$-6 -6 \lambda + \lambda + \lambda^2 + 12=0,$$  

$$\lambda^2 + 5 \lambda + 6=0, \Rightarrow ~\lambda_1 = \frac{5 + 1}{2} =3, ~\lambda_2 = \frac{5 - 1}{2}= 2$$

2. Теперь найдем собственные векторы, подставив полученные собственные значения в выражение $\textbf{A}x=\lambda x$:

* Для $\lambda = 3$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
3
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

$$\begin{cases}
-x_{1}-6x_{2}= 3x_{1}, \\
2x_{1}+6x_{2}= 3x_{2}
\end{cases} $$ 

$$\begin{cases}
-x_{1}-6x_{2} - 3x_{1} =0, \\
2x_{1}+6x_{2} - 3x_{2} =0
\end{cases} $$ 

$$\begin{cases}
-4x_{1} = 6x_{2}, \\
2x_{1} = - 3x_{2}
\end{cases} $$ 

$$\begin{cases}
6x_{2} - 6x_{2} = 0, \\
x_{1} = - \frac{3}{2}x_{2}
\end{cases}$$ 

$$\begin{cases}
x_{2} \forall, \\
x_{1} = - \frac{3}{2}x_{2}
\end{cases}$$  

Если $x_{2} = 1, ~то~ x_{1} = -\frac{3}{2}$

Собственный вектор $x = (-\frac{3}{2}, 1)$

* Для $\lambda = 2$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
2
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

$$\begin{cases}
-x_{1}-6x_{2}= 2x_{1}, \\
2x_{1}+6x_{2}= 2x_{2}
\end{cases} $$ 

$$\begin{cases}
-3x_{1}= 6x_{2}, \\
2x_{1}= -4x_{2}
\end{cases} $$

$$\begin{cases}
-2x_{2}= -2x_{2}, \\
x_{1}= -2x_{2}
\end{cases} $$

$$\begin{cases}
x_{2} \forall, \\
x_{1}= -2x_{2}
\end{cases} $$  

Если $x_{2} = 1, ~то~ x_{1} = -2$

Собственный вектор $x = (-2, 1)$

In [22]:
a = np.array([[-1, -6], [2, 6]])
w, v = eig(a)
print(f'Собственные значения: {w}\nСобственные векторы: \n{v}')

Собственные значения: [2. 3.]
Собственные векторы: 
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$


Показать, что __любой__ вектор является для него собственным.

1. Найдем собственные значения 

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)^2=0,$$

$$ \lambda_1 = \lambda_2 = -1$$

2. Теперь найдем собственные векторы, подставив собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
-1
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

$$\begin{cases}
-x_{1}-0 \cdot x_{2}= -x_{1}, \\
0 \cdot x_{1}- 1x_{2}= -x_{2}
\end{cases} $$ 

$$\begin{cases}
0 =0, \\
0 =0
\end{cases} \Rightarrow 
\begin{cases}
x_1 \forall, \\
x_2 \forall
\end{cases}$$   

Следовательно, любой вектор линейного оператора А является собственным

In [23]:
a = np.array([[-1, 0], [0, -1]])
w, v = eig(a)
print(f'Собственные значения: {w}\nСобственные векторы: \n{v}')

Собственные значения: [-1. -1.]
Собственные векторы: 
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

$$\begin{cases}
1+1=\lambda \\ 
-1+3 = \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}$$

Таким образом, вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=2$

In [27]:
a = np.array([[1, 1], [-1, 3]])
w, v = eig(a)
print(f'Собственные значения: {w}\nСобственные векторы: \n{v}')

Собственные значения: [2.00000002 1.99999998]
Собственные векторы: 
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\begin{cases}
3\lambda=-3 \cdot 3\\ 
3\lambda=-3 \cdot 3\\
-4\lambda=-4 \cdot 3
\end{cases} \Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}$$

Такая система не имеет смысла, следовательно, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [28]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = eig(a)
print(f'Собственные значения: {w}\nСобственные векторы: \n{v}')

Собственные значения: [ 3. -3.  3.]
Собственные векторы: 
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
