In [33]:
import numpy as np
from numpy.linalg import matrix_rank

### Часть 1  

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

$$rank \tilde{A} = rank A = 3, ~n=4$$  
Система имеет бесконечное множество решений  
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4, \\
x_{4} = c
\end{cases} \Rightarrow 
\begin{cases}
x_{1}=2c +\frac{3c-4}{2} - \frac{13c}{2} = -3c-2, \\
x_{2}=\frac{3c-4}{2} +5c +2 = \frac{13c}{2}, \\
x_{3}=\frac{3c-4}{2}, \\
x_{4} = c
\end{cases}$$

Если $c=1$, то частное решение системы будет: 
$$\begin{cases}
x_{1}= -5, \\
x_{2}=6.5, \\
x_{3}=-0.5, \\
x_{4} = 1
\end{cases}$$

Общее решение системы:
$$\begin{cases}
x_{1}= -3c-2, \\
x_{2}=\frac{13c}{2}, \\
x_{3}=\frac{3c-4}{2}, \\
x_{4} = c
\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    

In [36]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
a_tilda = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])

matrix_rank(a), matrix_rank(a_tilda)

(3, 3)

$$rank \tilde{A} = rank A = 3, ~n=3$$  
Система совместна, имеет единственное решение 

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [38]:
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
a_tilda = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

matrix_rank(a), matrix_rank(a_tilda)

(1, 2)

$$rank \tilde{A} \neq rank A$$  
Система несовместна, не имеет решений

 в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [40]:
a = np.array([[1, 2, 5], [3, 1, -8]])
a_tilda = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

matrix_rank(a), matrix_rank(a_tilda)

(2, 2)

$$rank \tilde{A} = rank A = 2, ~n=3$$  
Система совместна, имеет бесконечное множество решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [42]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
a_tilda = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])

matrix_rank(a), matrix_rank(a_tilda)

(4, 4)

$$rank \tilde{A} = rank A = 4, ~n=4$$  
Система совместна, имеет единственное решение 

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c -7a
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c -2b +a
\end{matrix}
\end{pmatrix}
$$

Система будет несовместной при $c-2b+a \neq 0$

### Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

 а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$ 
$$det A = \begin{vmatrix}
1 & -2\\ 
3 & -4
\end{vmatrix} = -4 + 6 = 2  \neq 0,$$ следовательно, система совместна.

$$det A_1 = \begin{vmatrix}
1 & -2\\ 
7 & -4
\end{vmatrix} = -4 + 14 = 10$$
$$det A_2 = \begin{vmatrix}
1 & 1\\ 
3 & 7
\end{vmatrix} = 7 - 3 = 4$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2,$$  

 б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$  

Найдем определитель матрицы коэффициентов:

$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
1\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+5
\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=2(1 + 12) +1 (1 + 6) + 5(4 - 2) = 43 \neq 0,$$

следовательно, система совместна.

$$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
10(1 +12) +1(-2 +3) +5 (-8-1) = 130 + 1 -45 = 86$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
2(-2 +3) - 10(1 + 6) +5 (1 + 4) = 2 -70 +25 = -43$$

$$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
2(1 + 8) +1 (1 + 4) + 10(4-2) = 18 + 5 +20 = 43$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$$

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
 
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix} = 
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix} = 
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix} = 
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix} = U$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

In [45]:
l = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
u = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])

print(l @ u)

[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix} = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
4 & 18 & 45 & 17
\end{pmatrix} = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix} = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix} = U$$

$$L = \begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$$

In [47]:
l = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
u = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])

print(l @ u)

[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


  
__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

а)$$A = \begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix} $$
1) Найдем матрицы LU:  

$$ 
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 3.5 & -9.5
\end{pmatrix} = \begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix} = U$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}$$

2) Решим $Ly = b$  

$$\begin{cases}
y_{1}=1 \\
\frac{11}{2}y_1 + y_2  =-6 \\
\frac{9}{2}y_1 +\frac{7}{3}y_2 + y_3=-5
\end{cases} \Rightarrow 
\begin{cases}
y_{1}=1 \\
y_2  =-\frac{23}{2} \\
y_3=\frac{52}{3}
\end{cases}$$

3) Решим $Ux = y$  

$$\begin{cases}
2x_1 + x_2 + 3x_3=1 \\
 \frac{3}{2}x_2 -\frac{23}{2}x_3  =-\frac{23}{2} \\
\frac{52}{3}x_3=\frac{52}{3}
\end{cases} \Rightarrow
\begin{cases}
x_1 = -1 \\
x_2 = 0 \\
x_3=1
\end{cases}
$$


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$


1) Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9} = -5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9} = 5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 +25 \right)=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

2) Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases} \Rightarrow \begin{cases}
y_{1} = 59, \\
y_{2}= (-460+5 \cdot 59)/5 = -33, \\
y_{3}=(193 - 5 \cdot 59 - 2 \cdot (-33))/3 = -12.
\end{cases}$$

3) решим систему $L^{T}x=y:$

$$\begin{cases}
9 x_{1} - 5 x_{2} + 5x_{3}= 59, \\
5 x_{2} + 2x_{3} = -33, \\
3x_{3} = -12.
\end{cases} \Rightarrow \begin{cases}
x_{1} = (59 -5 (-4) + 5 (-5)) / 9 = 6, \\
x_{2} = (-33 + 8)/ 5 = -5, \\
x_{3} = -4.
\end{cases}$$

In [ ]:
__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.