### Часть 1

In [4]:
import numpy as np
from sympy import *
from numpy.linalg import matrix_rank, inv

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


   а) не определены;
    
   б) не определены;
    
   в) определены: $A\times B$ матрица -  $8\times 8$, $B\times A$ матрица -  $3\times 3$;
    
   г) определены: $A\times B = B\times A$  матрица -  $4\times 4$.
    

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [50]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

$A + B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

In [53]:
print('sum: \n', a+b)

sum: 
 [[ 5 -3]
 [ 3  5]]


$A \times B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \times \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1\cdot 4 + 0 & -1 - 2 \cdot 5 \\ 
3\cdot 4 + 0 & -3+0
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$  

$B \times A = \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \times 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}  = \begin{pmatrix}
4\cdot 1 - 1 \cdot 3 & -2 \cdot 4 - 0 \\ 
0\cdot 1 + 5 \cdot 3 &  -2 \cdot 0 + 5 \cdot 0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [8]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a@b, b@a

(array([[  4, -11],
        [ 12,  -3]]),
 array([[ 1, -8],
        [15,  0]]))

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3 \times \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} -2 \times \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} +4\times \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} -\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [54]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$.

$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} = \begin{pmatrix}
(4\cdot 4 + 1 \cdot 1) & (4\cdot 5 - 2) & (4\cdot 2 + 3 \cdot 1) \\ 
(5\cdot 4 - 2 \cdot 1) & (5\cdot 5 + 2 \cdot 2) & (5\cdot 2 - 3 \cdot 2) \\ 
(2\cdot 4 + 3) & (2\cdot 5 - 2 \cdot 3) & (2\cdot 2 + 3 \cdot 3)
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\ 
11 & 4 & 13
\end{pmatrix}$   

$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} \times \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
(4\cdot 4 + 5 \cdot 5 + 2 \cdot 2) & (4\cdot 1 - 2\cdot 5 + 3 \cdot 2) \\ 
(4\cdot 1 - 5 \cdot 2 + 2 \cdot 3) & (1\cdot 1 + 2\cdot 2 + 3 \cdot 3)
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\ 
0 & 14 
\end{pmatrix}$.

In [56]:
a = np.array([[4, 1], [5, -2], [2, 3]])
aat = a@a.T
ata =a.T@a
print(f'Matrix: \n{a}\n AAt: \n{aat} \n AtA: \n{ata}')

Matrix: 
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
 AAt: 
[[17 18 11]
 [18 29  4]
 [11  4 13]] 
 AtA: 
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [114]:
def matrix_multiply(matrix1, matrix2):
    n = len(matrix1)
    m = len(matrix2[0])
    mult = [[0 for i in range(n)] for i in range(m)]
    for i in range(n):
      for j in range(m):
        for k in range(len(matrix2)):
           mult[i][j] += matrix1[i][k] * matrix2[k][j]
    return mult

def matrix_multiply_test():
    a = [[1, -2], [3, 0]]
    b = [[4, -1], [0, 5]]
    c = [[1, 2, 3], [4, 5, 6]]
    d = [[1, 2], [3, 4], [5, 6]]
    print("Test1 - ", "OK" if matrix_multiply(a, b) == [[ 4, -11], [ 12,  -3]] else "False")
    print("Test2 - ", "OK" if matrix_multiply(c, d) == [[22, 28], [49, 64]] else "False")

matrix_multiply_test()

Test1 -  OK
Test2 -  OK


### Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^2x + cos^2x = 1$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180$$

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1(45 - 48) -2 (36 - 42) +3 (32 - 35) = -3 + 12 - 9 = 0$$

In [82]:
x = Symbol('x')
A = Matrix([[sin(x), -cos(x)], [cos(x), sin(x)]])
A.det()

sin(x)**2 + cos(x)**2

In [111]:
# B = Matrix([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
# B.det()
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
det(b)

180.0

In [9]:
from numpy.linalg import det
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{det(C):.0f}')

-0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = det(A) \times det(A) = 4 \cdot 4 = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A) = 2^n \cdot det(a) = 2^n \cdot 4$.


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица является вырожденной, если ее определитель равен 0.
$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2(-14 \cdot(13) -6 \cdot 7) -7(4 \cdot 13+ 6 \cdot 3) -3(4 \cdot 7 -3 \cdot 14) = 448 -490 + 42 = 0 \\ \Rightarrow ~вырожденная$$ 

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} = \begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
1 & 1 & 1
\end{pmatrix} = \begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1\\ 
\end{pmatrix} \Rightarrow rankA = 2$  

1. Из третьей строки вычитаем первую
2. Третью строку сокращаем, из первой вычитаем вторую

In [106]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n {a} \nранг: {matrix_rank(a)}')

Матрица:
 [[1 2 3]
 [1 1 1]
 [2 3 4]] 
ранг: 2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix} = \begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix} = \begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix} \Rightarrow rankA = 2$  

1. Из третьей строки вычитаем первую
2. Третью строку сокращаем, из первой вычитаем третью

In [107]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица:\n {b} \nранг: {matrix_rank(b)}')

Матрица:
 [[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]] 
ранг: 3


__5*.__ Алгоритм для вычисления определителя

In [13]:
# для теста высчитаем определители разных матриц
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1, 0], [0, 5, 1]])
c = np.array([[1, 2, 3, 4], [1, 4, 5, 6], [2, 7, 8, 0], [1, 4, 2, 8]])
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'det a = {det(a):.0f},\ndet c = {det(c):.0f},\ndet d = {det(d):.0f}')

det a = 6,
det c = -70,
det d = -0


In [2]:
def my_det(matrix):
    n = len(matrix)
    assert n == len(matrix[0]), 'Matrix dimention error'
    if n == 1:
        return matrix[0][0]
    elif n == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    else:
        det = 0
        for j in range(n):
            minor = [string[:j] + string[j+1:] for string in (matrix[:0]+matrix[1:])]
            det += matrix[0][j]* (-1)**(j)*my_det(minor)
    return det

def my_det_test():
    a = [[1, -2], [3, 0]]
    b = [[4, -1, 0], [0, 5, 1]]
    c = [[1, 2, 3, 4], [1, 4, 5, 6], [2, 7, 8, 0], [1, 4, 2, 8]]
    d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    e = [[1]]
    print("Test1 -", "OK" if my_det(a) == 6 else "False")
    print("Test2 -", "OK" if my_det(c) == -70 else f"{print(my_det(c))} - False")
    print("Test3 -", "OK" if my_det(d) == 0 else f"{print(my_det(d))} - False")
    try:
        my_det(b)
    except AssertionError:
        print("Test4 - OK")
    print("Test5 -", "OK" if my_det(e) == 1 else "False")

my_det_test()

Test1 - OK
Test2 - OK
Test3 - OK
Test4 - OK
Test5 - OK
